platform :ios, '8.0'
use_frameworks!

# ignore all warnings from all Pods
inhibit_all_warnings!

target :'XSkillz' do
    pod 'Alamofire'
    pod 'AlamofireImage'
    pod 'Crashlytics'
    pod 'DeviceKit'
    pod 'Fabric'
    pod 'JHChainableAnimations'
    pod 'ReactKit'
    pod 'RealmSwift'
    pod 'SnapKit'
    pod 'Typhoon'
    pod 'UIColor_Hex_Swift'
end