platform :ios, '9.0'
use_frameworks!

# ignore all warnings from all Pods
inhibit_all_warnings!

target :'XSkillz' do
    pod 'Alamofire'
    pod 'AlamofireImage'
    pod 'Crashlytics'
    pod 'DeviceKit'
    pod 'Fabric'
    pod 'JHChainableAnimations'
    pod 'SwiftTask', :git => 'https://github.com/ReactKit/SwiftTask/', :branch => 'swift/3.0'
    pod 'RealmSwift'
    pod 'SnapKit'
    pod 'UIColor_Hex_Swift'
end
